# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-23 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-created',)},
        ),
    ]
